"""ComfyUI-Sharp nodes aggregation."""


from .plytohtml import NODE_CLASS_MAPPINGS as PLYTOHTML_MAPPINGS
from .plytohtml import NODE_DISPLAY_NAME_MAPPINGS as PLYTOHTML_DISPLAY_MAPPINGS
from .plytoimages import NODE_CLASS_MAPPINGS as RENDER_PLY_MAPPINGS
from .plytoimages import NODE_DISPLAY_NAME_MAPPINGS as RENDER_PLY_DISPLAY_MAPPINGS

# Aggregate all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(PLYTOHTML_MAPPINGS)
NODE_CLASS_MAPPINGS.update(RENDER_PLY_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(PLYTOHTML_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RENDER_PLY_DISPLAY_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
