"""SharpRenderPLY node for ComfyUI-Sharp."""

import os
import sys
from pathlib import Path
import torch
import numpy as np
from PIL import Image
import tempfile
import shutil

sys.path.insert(0, str(Path(__file__).parent.parent / "sharp-render-splat-transform"))

from pythonRun import SplatTransform


class SharpPLYToImages:
    """
    Render PLY file from SharpPredict to IMAGE.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "ply_path": ("STRING", {
                    "forceInput": True,
                    "tooltip": "Path to PLY file generated by SharpPredict"
                }),
                "width": ("INT", {
                    "default": 1536,
                    "min": 64,
                    "max": 4096,
                    "step": 1,
                    "tooltip": "Rendered image width in pixels"
                }),
                "height": ("INT", {
                    "default": 1536,
                    "min": 64,
                    "max": 4096,
                    "step": 1,
                    "tooltip": "Rendered image height in pixels"
                }),
                "fov": ("FLOAT", {
                    "default": 40.0,
                    "min": 1.0,
                    "max": 179.0,
                    "step": 1.0,
                    "tooltip": "Field of view in degrees"
                }),
                "frames": ("INT", {
                    "default": 1,
                    "min": 1,
                    "max": 360,
                    "step": 1,
                    "tooltip": "Number of frames to render (orbit animation)"
                }),
                "radius": ("FLOAT", {
                    "default": 2.0,
                    "min": 0.1,
                    "max": 100.0,
                    "step": 0.1,
                    "tooltip": "Camera orbit radius"
                }),
            },
            "optional": {
                "target_x": ("FLOAT", {
                    "default": 0.0,
                    "step": 0.1,
                    "tooltip": "Camera target X position"
                }),
                "target_y": ("FLOAT", {
                    "default": 0.0,
                    "step": 0.1,
                    "tooltip": "Camera target Y position"
                }),
                "target_z": ("FLOAT", {
                    "default": 1.0,
                    "step": 0.1,
                    "tooltip": "Camera target Z position"
                }),
                "swing_angle": ("FLOAT", {
                    "default": 14.0,
                    "min": 1.0,
                    "max": 180.0,
                    "step": 1.0,
                    "tooltip": "Swing angle range in degrees (e.g., 14 means -7 to 7)"
                }),
            }
        }

    RETURN_TYPES = ("IMAGE", )
    RETURN_NAMES = ("image", )
    FUNCTION = "render"
    CATEGORY = "SHARP"
    OUTPUT_NODE = True
    DESCRIPTION = "Render PLY file from SharpPredict to IMAGE using orbit-render tool."

    def render(self, ply_path: str, width=1536, height=1536, fov=40.0, frames=1, radius=2.0,
               target_x=0.0, target_y=0.0, target_z=1.0, swing_angle=14.0):
        """
        Render PLY file to images using orbit-render.
        
        Args:
            ply_path: Path to input PLY file
            width: Image width in pixels
            height: Image height in pixels
            fov: Field of view in degrees
            frames: Number of frames to render
            radius: Camera orbit radius
            target_x: Camera target X position
            target_y: Camera target Y position
            target_z: Camera target Z position
            swing_angle: Swing angle range in degrees (e.g., 14 means -7 to 7)
            
        Returns:
            ComfyUI IMAGE tensor: (B, H, W, C) float32 0-1
        """
        temp_dir = tempfile.mkdtemp(prefix="comfyui_splat_")
        
        try:
            splat = SplatTransform()
            
            frame_files = splat.render_orbit(
                input_ply=ply_path,
                output_dir=temp_dir,
                frames=frames,
                radius=radius,
                fov=int(fov),
                width=width,
                height=height,
                target=(target_x, target_y, target_z),
                swing_angle=swing_angle,
                quiet=True
            )
            
            if not frame_files:
                raise RuntimeError("No frames were generated")
            
            images = []
            for frame_file in frame_files:
                img = Image.open(frame_file)
                img_array = np.array(img).astype(np.float32) / 255.0
                images.append(img_array)
            
            img_tensor = torch.from_numpy(np.stack(images))
            
            if img_tensor.ndim == 3:
                img_tensor = img_tensor.unsqueeze(0)
            
            if img_tensor.ndim == 4 and img_tensor.shape[-1] == 3:
                pass
            elif img_tensor.ndim == 4 and img_tensor.shape[-1] == 4:
                img_tensor = img_tensor[..., :3]
            
            return (img_tensor, )
            
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)


# Node mappings for ComfyUI
NODE_CLASS_MAPPINGS = {
    "SharpPLYToImages": SharpPLYToImages
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SharpPLYToImages": "Sharp PLY To Images"
}
