"""SharpRenderPLY node for ComfyUI-Sharp."""

import os
import sys
from pathlib import Path
import time

sys.path.insert(0, str(Path(__file__).parent.parent / "sharp-render-splat-transform"))

from pythonRun import SplatTransform

try:
    import folder_paths
    OUTPUT_DIR = folder_paths.get_output_directory()
except ImportError:
    OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")


class SharpPLYToHTML:
    """
    Render PLY file from SharpPredict to HTML.
    """

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "ply_path": ("STRING", {
                    "forceInput": True,
                    "tooltip": "Path to PLY file generated by SharpPredict"
                }),
                "output_prefix": ("STRING", {
                    "default": "splat_html",
                    "tooltip": "Prefix for output HTML file name"
                }),
            },
            "optional": {
                "custom_output_dir": ("STRING", {
                    "default": "",
                    "tooltip": "Custom output directory (empty to use ComfyUI output directory)"
                }),
            }
        }

    RETURN_TYPES = ("STRING", )
    RETURN_NAMES = ("html_path", )
    FUNCTION = "render_ply_to_html"
    CATEGORY = "SHARP"
    OUTPUT_NODE = True
    DESCRIPTION = "Render PLY file from SharpPredict to HTML."

    def render_ply_to_html(self, ply_path: str, output_prefix: str = "splat_html", custom_output_dir: str = ""):
        """
        Render PLY file to HTML viewer.
        
        Args:
            ply_path: Path to input PLY file
            output_prefix: Prefix for output HTML file name
            custom_output_dir: Custom output directory (empty to use ComfyUI output directory)
            
        Returns:
            Path to generated HTML file
        """
        if not os.path.exists(ply_path):
            raise FileNotFoundError(f"PLY file not found: {ply_path}")
        
        timestamp = int(time.time())
        
        if custom_output_dir:
            output_dir = custom_output_dir
        else:
            output_dir = OUTPUT_DIR
        
        os.makedirs(output_dir, exist_ok=True)
        
        output_filename = f"{output_prefix}_{timestamp}.html"
        output_html = os.path.join(output_dir, output_filename)
        
        try:
            splat = SplatTransform()
            html_path = splat.generate_html_viewer(
                input_ply=ply_path,
                output_html=output_html,
                quiet=False
            )
            
            if not os.path.exists(html_path):
                raise RuntimeError(f"HTML file was not generated: {html_path}")
            
            return (html_path, )
            
        except Exception as e:
            raise RuntimeError(f"Failed to generate HTML viewer: {str(e)}")


# Node mappings for ComfyUI
NODE_CLASS_MAPPINGS = {
    "SharpPLYToHTML": SharpPLYToHTML
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SharpPLYToHTML": "Sharp PLY To HTML"
}
